tasklist/urls.py
from django.conf.urls import url
from django.contrib import admin

from tasklist import views

urlpatterns = [
    url(r'^mine/$', views.view_list, {'filter_type': 'mine'}, name="list-mine"),
    url(r'^task/(?P<task_id>\d{1,6})$', views.view_task, name='task_detail'),
    url(r'^incomplete/$', views.view_list, {'filter_type': 'incomplete'}, name='incomplete_tasks'),
    url(r'^completed/$', views.view_list, {'view_completed': True}, name='completed_tasks'),
    url(r'^recent/added/$', views.view_list, {'filter_type': 'recent-add'}, name="recently_added"),
    url(r'^recent/completed/$', views.view_list, {'filter_type': 'recent-complete'}, name="recently_completed"),
    url(r'^admin/', admin.site.urls),
]

tasklist/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.contrib.auth.models import User
from django_enumfield import enum
from django.utils.encoding import python_2_unicode_compatible


class PriorityType(enum.Enum):
    LOW = 0
    MEDIUM = 1
    HIGH = 2
    labels = {
        LOW: 'Low',
        MEDIUM: 'Medium',
        HIGH: 'High'
    }


@python_2_unicode_compatible
class Item(models.Model):
    title = models.CharField(max_length=140)
    created_date = models.DateField(auto_now=True)
    due_date = models.DateField(blank=True, null=True, )
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(User)
    priority = enum.EnumField(PriorityType, default=PriorityType.MEDIUM)
    note = models.TextField(blank=True, null=True)

    def overdue_status(self):
        if self.due_date and datetime.date.today() > self.due_date:
            return True
        else:
            return False

    def priority_label(self):
        if self.priority:
            return PriorityType.get(self.priority).label
        else:
            return ''


    def __str__(self):
        return self.title

    def save(self):
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Item, self).save()

    class Meta:
        ordering = ["-due_date", "-priority"]

tasklist/forms.py
from django import forms
from django.forms import ModelForm

from tasklist.models import Item


class AddItemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddItemForm, self).__init__(*args, **kwargs)

    due_date = forms.DateField(
        required=False,
        widget=forms.DateTimeInput(attrs={'class': 'due_date_picker'})
    )

    title = forms.CharField(
        widget=forms.widgets.TextInput(attrs={'size': 35})
    )

    note = forms.CharField(widget=forms.Textarea(), required=False)

    class Meta:
        model = Item
        exclude = []


class EditItemForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Item
        exclude = ('created_date', 'created_by',)

tasklist/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from tasklist.forms import AddItemForm, EditItemForm
from tasklist.models import Item
from tasklist.utils import mark_done, undo_completed_task

@login_required()
def view_list(request, filter_type='mine', view_completed=False):

    mark_done(request, request.POST.getlist('mark_done'))
    undo_completed_task(request, request.POST.getlist('undo_completed_task'))

    thedate = datetime.datetime.now()
    created_date = "%s-%s-%s" % (thedate.year, thedate.month, thedate.day)

    if filter_type == "mine":
        task_list = Item.objects.filter(created_by=request.user, completed=False).order_by('due_date', '-priority')
        completed_list = Item.objects.filter(created_by=request.user, completed=True).order_by('due_date', '-priority')
    elif filter_type == "recent-add":
        task_list = Item.objects.filter(
            created_by=request.user,
            completed=False).order_by('-created_date')[:50]
    elif filter_type == "recent-complete":
        task_list = Item.objects.filter(
            created_by=request.user,
            completed=True).order_by('-completed_date')[:50]
    else:
        task_list = Item.objects.filter(created_by=request.user, completed=False).order_by('due_date', '-priority')
        completed_list = Item.objects.filter(created_by=request.user, completed=True).order_by('due_date', '-priority')

    if request.POST.getlist('add_task'):
        form = AddItemForm(request.POST, initial={
            'created_by': request.user.id
        })

        if form.is_valid():
            new_task = form.save()

            messages.success(request, "New task \"{t}\" has been added.".format(t=new_task.title))
            return HttpResponseRedirect(request.path)
    else:
        if filter_type != "mine" and filter_type != "recent-add" and filter_type != "recent-complete":
            form = AddItemForm(initial={
                'created_by': request.user.id,
            })

    return render(request, 'tasklist/view_list.html', locals())

@login_required()
def view_task(request, task_id):
    task = get_object_or_404(Item, pk=task_id)

    if task.created_by == request.user:
        if request.POST:
            form = EditItemForm(request.POST, instance=task)

            if form.is_valid():
                form.save()
                messages.success(request, "The task has been edited.")

                return HttpResponseRedirect(reverse('incomplete_tasks'))
        else:
            form = EditItemForm(instance=task)
            if task.due_date:
                thedate = task.due_date
            else:
                thedate = datetime.datetime.now()
    else:
        messages.info(request, "You do not have permission to view/edit this task.")

    return render(request, 'tasklist/view_task.html', locals())

tasklist/templates/tasklist/base.html
{% load staticfiles %}

{% block extrahead %}
<!-- CSS and JavaScript for django-tasklist -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" type="text/css" href="{% static 'tasklist/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'tasklist/css/bootstrap-theme.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'tasklist/css/styles.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'tasklist/css/jquery-ui.min.css' %}" />
<script src="{% static 'tasklist/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'tasklist/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>
<script src="{% static 'tasklist/js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'tasklist/js/jquery-ui.js' %}" type="text/javascript"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->


<script type="text/javascript" charset="utf-8">
    // thedate.x comes from the edit_task view. If this is a new entry,
    // thedate won't be present and datepicker will fall back on the default (today).
    $(document).ready(function(){
        $('#id_due_date').datepicker({defaultDate: new Date({{thedate.year}}, {{thedate.month}} - 1, {{thedate.day}}),});
    });
</script>
{% endblock extrahead %}

<body>
<nav class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Tasks4All</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'list-mine' %}">Home</a></li>
                <li><a  class="todo" href="{% url 'completed_tasks' %}">Completed</a></li>
                <li><a class="todo" href="{% url 'incomplete_tasks' %}">Incomplete</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#about">About</a></li>
                <li><a href="#contact">Contact</a></li>
                <li><a href="#help">Help</a></li>
                <li><a href="#">Welcome {{ request.user }}</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
</body>

{% block content %}
{% endblock %}

tasklist/templates/tasklist/view_list.html
{% extends "tasklist/base.html" %}

{% block content %}

<script type="text/javascript">
    $(document).ready(function() {
        $('#AddTask').hide();
        $('#slideToggle').click(function(){
            $(this).siblings('#AddTask').slideToggle();
        });
    });
</script>



<form action="" method="POST">
    {% csrf_token %}

    {% if not view_completed %}

    <h3>Incomplete tasks</h3>

    <div class="table-responsive">
        <table border="0" class="table table-striped table-bordered">
            <tr class="row">
                <th class="col-xs-6 col-sm-4">Done</th>
                <th class="col-xs-6 col-sm-4">Task</th>
                <th class="col-xs-6 col-sm-4">Priority</th>
                <th class="col-xs-6 col-sm-4">Due on</th>
                <th class="col-xs-6 col-sm-4">Owner</th>
                <th class="col-xs-6 col-sm-4">Note</th>
            </tr>
            {% for task in task_list %}
            <tr class="row" id="{{ task.id }}">
                <td class="col-xs-6 col-sm-4"><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}">   </td>
                <td class="col-xs-6 col-sm-4"><a href="{% url 'task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
                <td class="col-xs-6 col-sm-4">{{ task.priority_label }}</td>
                <td class="col-xs-6 col-sm-4">
                    {% if task.overdue_status %}<span class="overdue">{% endif %}
							{{ task.due_date|date:"m/d/Y" }}
						{% if task.overdue_status %}</span>{% endif %}
                </td>
                <td class="col-xs-6 col-sm-4">{{ task.created_by }}</td>
                <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
                {% if list_slug == "mine" %}
                <td><a href="{% url 'incomplete_tasks' %}">{{ task.list }}</a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </table></div>

    <p><input type="submit" name="mark_tasks_done" value="Save..."  class="btn btn-sm btn-primary"></p>


    {% else %}

    <h3>Completed tasks</h3>


    <div class="table-responsive">
        <table border="0" class="table table-striped table-bordered">
            <tr class="row">
                <th class="col-xs-6 col-sm-4">Undo</th>
                <th class="col-xs-6 col-sm-4">Task</th>
                <th class="col-xs-6 col-sm-4">Priority</th>
                <th class="col-xs-6 col-sm-4">Completed on</th>
                <th class="col-xs-6 col-sm-4">Note</th>
            </tr>

            {% for task in completed_list %}
            <tr class="row">
                <td class="col-xs-6 col-sm-4"><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">   </td>
                <td class="col-xs-6 col-sm-4"><a href="{% url 'task_detail' task.id %}">{{ task.title|truncatewords:20 }}</a></td>
                <td class="col-xs-6 col-sm-4">{{ task.priority_label }}</td>
                <td class="col-xs-6 col-sm-4">{{ task.completed_date|date:"m/d/Y" }}</td>
                <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
            </tr>
            {% endfor %}

        </table>
    </div>

    <p><input type="submit" name="mark_tasks_undone" value="Save..."  class="btn btn-sm btn-primary"></p>
</form>

{% endif %}


<p id="slideToggle" class="btn btn-sm btn-link"><strong>Add More Tasks</strong></p>

<div id="AddTask">
    <div class="table-responsive">
        <table class="table" border="0" cellspacing="5" cellpadding="5">
            <tr class="row">
                <td class="col-xs-6 col-sm-4">{{ form.title.errors }}</td>
                <td class="col-xs-6 col-sm-4">{{ form.due_date.errors }}</td>
            </tr>
            <tr class="row">
                <td class="col-xs-6 col-sm-4"><label for="id_title">Task:</label> {{ form.title }}</td>
                <td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
            </tr>
            <tr class="row">
                <td class="col-xs-6 col-sm-4"><label for="id_note">Note:</label>
                    {{ form.note }}
                </td>
            </tr>
            <tr class="row">
                <td class="col-xs-6 col-sm-4"><label>Priority:</label> {{ form.priority }}</td>
            </tr>
            <tr class="row">
                <td colspan=2 align="middle" class="col-xs-6 col-sm-4"><input type="submit" name="add_task" value="Add task" class="btn btn-sm btn-primary"></td>
            </tr>
        </table>
    </div>

    <input type="hidden" name="created_by" value="{{ request.user.id }}" id="id_created_by">

    <input type="hidden" name="created_date" value="{{ created_date }}" id="id_created_date">

</div>


{% endblock %}

tasklist/templates/tasklist/view_task.html
{% extends "tasklist/base.html" %}

{% block title %}Task: {{ task.title }}{% endblock %}

{% block content %}

<h3>{{ task }}</h3>

<form action="" method="POST">
    {% csrf_token %}

    <div id="EditTask">

        <div class="table-responsive">
            <table class="table">
                <tr class="row">
                    <td class="col-xs-6 col-sm-4">Title:</td>
                    <td>{{ form.title }}</td>
                </tr>

                <tr class="row">
                    <td class="col-xs-6 col-sm-4">Due:</td>
                    <td>{{ form.due_date }}</td>
                </tr>

                <tr class="row">
                    <td class="col-xs-6 col-sm-4" valign="top">Note:</td>
                    <td class="col-xs-6 col-sm-4">{{ form.note }}</td>
                </tr>

                <tr class="row">
                    <td class="col-xs-6 col-sm-4">Priority:</td>
                    <td class="col-xs-6 col-sm-4">{{ form.priority }}</td>
                </tr>
                <tr class="row">
                    <td class="col-xs-6 col-sm-4">Completed:</td>
                    <td class="col-xs-6 col-sm-4">{{ form.completed }}</td>
                </tr>
                <tr class="row">
                    <td colspan=2 align="middle" class="col-xs-6 col-sm-4"><input type="submit"
                                                                                  class="btn btn-sm btn-primary"
                                                                                  name="edit_task" value="Edit task">
                    </td>
                </tr>

            </table>
        </div>
    </div>

    <hr/>

</form>

{% endblock %}